### ISSUE TITLE
Protect access to XMLRPC server

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#286]
cloud_status and cloud_admin use a simple XMLRPC server that does not have authentication. It would be good to protect access to this, so that root privileges are required to perform cloud_admin actions. Otherwise sophisticated and unprivileged local users might be able to e.g. shut down VMs.

**Comment by rptaylor** [comment]
This should be more of a priority for Cloud Scheduler systems that provide access to many users.

**Comment by mhpx** [comment]
#412 Should make this a lot easier to do.
