### ISSUE TITLE
CS fails to quickrestart properly

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#335]
CS appears to be running correctly beforehand:

$ sudo /etc/init.d/cloud_scheduler status
cloud_scheduler is running with PID 26605.
$ ps -ef | grep cloud
root     26605     1  0 Aug11 pts/0    00:00:00 sudo nohup /usr/local/bin/python2.7 /usr/local/bin/cloud_scheduler
root     26607 26605  8 Aug11 pts/0    01:49:10 /usr/local/bin/python2.7 /usr/local/bin/cloud_scheduler
$ cat /var/run/cloud_scheduler.pid
26605

But doing a quickrestart fails:

$ sudo /etc/init.d/cloud_scheduler quickrestart
Setting Quick Exit Flag for cloud_scheduler:                [  OK  ]
Stopping cloud_scheduler:kill 26605: No such process
                [  OK  ]
Starting cloud_scheduler:                [  OK  ]
$ ps -ef | grep cloud
root     26607     1  8 Aug11 pts/0    01:49:16 /usr/local/bin/python2.7 /usr/local/bin/cloud_scheduler

The "nohup" process is gone but the child is still running. It has to be killed -9 and then CS has to be started again.

**Comment by rptaylor** [comment]
Still happens regularly.

**Comment by mhpx** [comment]
whenever you see this happening could you do a cloud_status -x  and see which thread(s) is locking up. And grep to the log for the last message from that thread?

**Comment by rptaylor** [comment]
Still happens with the new script:

$ sudo /etc/init.d/cloud_scheduler quickrestart
Setting Quick Exit Flag for cloud_scheduler:kill 15622: No such process
				[  OK  ]
Stopping cloud_scheduler:kill 15622: No such process
				[  OK  ]
Starting cloud_scheduler:				[  OK  ]

$ cloud_status -x
Thread Heart beat times:
   Scheduler Thread(20): 9
   Cleanup Thread(35): 39
   VMPoller Thread(180): 73
   JobPoller Thread(35): 18
   MachinePoller Thread(15): 15

**Comment by rptaylor** [comment]
It even happened when CS was only running for ~ a minute since the previous quickrestart.

**Comment by rptaylor** [comment]
$ sudo /etc/init.d/cloud_scheduler quickrestart
Setting Quick Exit Flag for cloud_scheduler:				[  OK  ]
Stopping cloud_scheduler:kill 10478: No such process
				[  OK  ]
Starting cloud_scheduler:				[  OK  ]
$ cloud_status -x
Thread Heart beat times:
   Scheduler Thread(20): 19
   Cleanup Thread(35): 0
   VMPoller Thread(180): 134
   JobPoller Thread(35): 26
   MachinePoller Thread(15): 4

Are any of the threads hung? Anything to look for in the logs?
