### ISSUE TITLE
Remove requirement for unnecessary properties in cloud_resources.conf

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#357]
The parser complains if "networks:" is omitted, even though this property isn't needed.
As a workaround we leave the field empty. But it should be possible to remove the unnecessary field , with the same result as leaving it empty.

Likewise, for OpenStackNative clouds, the host and port for the EC2 interface shouldn't be needed, because auth_url is used instead.

Related to: https://github.com/hep-gc/cloud-scheduler/issues/354

**Comment by rptaylor** [comment]
Actually leaving it empty doesn't appear to work:

2015-02-06 16:53:25,429 - DEBUG - Scheduler - Unable to find network named:  on cc-east
2015-02-06 16:53:25,432 - ERROR - Scheduler - <type 'instance'> can't be encoded
2015-02-06 16:53:25,434 - DEBUG - Scheduler - Failed to create instance on cc-east

**Comment by rptaylor** [comment]
Actually that error may be caused by something else.

**Comment by mhpx** [comment]
https://github.com/hep-gc/cloud-scheduler/commit/0d1ef465df28b47563dd8206adf7392713aed352 should allow networks to be omitted from cloud_resources.conf now.

**Comment by mhpx** [comment]
the Port field isn't read in for openstack, or ec2 for that matter.. Port is only parsed in for Nimbus clouds.

**Comment by rptaylor** [comment]
Okay, has this update been applied on condor.heprc? If so I'll try removing networks, port, and host.
