### ISSUE TITLE
multithreaded VM shutdown

### ISSUE THREAD

**Issue by igable** [hep-gc/cloud-scheduler#358]
When thousands of jobs finish simultaneously this can necessitate the shutdown of many VMs simultaneously. This creates some problems when we run out of python threads to shut down all of these in paralllel when OpenStack is taking a long time to shutdown VMs.

**Comment by mhpx** [comment]
setting the timeout for the openstack connection has mostly solved this issue, no longer seeing the destroy threads getting hung and backlogged due to slow or hung responses  from openstack.
