### ISSUE TITLE
CS should handle condor contextualization itself

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#359]
CS needs VMs to have specific condor configurations. We stopped using the ec2contexthelper for this and it's currently done by user-specified scripts. However, CS should do this itself since it shouldn't be the users's responsibility.
It would also greatly simplify the cloud-init scripts we use!

Thanks.

**Comment by rptaylor** [comment]
Our cloud-init scripts are too large (34 KB) to use in the Openstack dashboard, so we don't have a good way to test or debug the cloud-init scripts (and there are some issues that need to be tested). 
So this should be a higher priority.

**Comment by rptaylor** [comment]
This would be really nice; any update?

**Comment by rptaylor** [comment]
This will be important for Cloud Scheduler systems that provide access to many users, to increase user-friendliness.

**Comment by mhpx** [comment]
this now resolved with the default.yaml stuff.
