### ISSUE TITLE
CS Hostname Issue

### ISSUE THREAD

**Issue by rd37** [hep-gc/cloud-scheduler#361]
If the host machine's hostname is mis-configured, then cloud-scheduler propagates the wrong hostname to the condor clients.

**Comment by rd37** [comment]
The bug/issue resulted when bellecs was migrated to a VM. The hostname on the VM was set to 'bellecs' rather than 'bellecs.heprc.uvic.ca', the CS was then writing 'bellecs' into the condor_config.local file for the condor_host variable. This caused the condor client to be unable to find the condor host.

**Comment by rptaylor** [comment]
But if CS doesn't know its hostname, what else can it do?
