### ISSUE TITLE
Complain louder about invalid syntax in config file

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#364]
We had "lacement_zone" instead of "placement_zone" in the CS config for who knows how long.
No error was visible, but the VMs were running in an unintended zone.

If there's invalid syntax in the config file, shouldn't CS print a error message to the log file, or even to the console and refuse to start running?

**Comment by rptaylor** [comment]
Similarly if "region" is not defined, CS dies without any error message. It should say something about missing a required config value.

**Comment by mhpx** [comment]
Will plan to refactor the parsing for the cloud_resources.conf and add checks for the required fields for each cloud as well as checking sections against the valid list to catch typos
