### ISSUE TITLE
gracefully retire instead of kill when reducing quota

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#366]
When reducing quota and quickrestarting, CS should retire VMs gracefully by default instead of killing them.
The alternative is cumbersome (disable, manually retire some, quickrestart).
This will also be important for the proposals about dynamic quota adjustment needed for the future.

**Comment by mhpx** [comment]
Seems to be working, need to add something to cloud_status to view which machines are waiting to retire as they currently do not show up in the normal cloud_status -m
