### ISSUE TITLE
Slipstream comparison

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#371]
Slipstream seems pretty similar to Cloud Scheduler:

http://sixsq.com/products/slipstream.html
http://sixsq.com/products/slipstream-tryme.html

It is an open-source system for provisioning resources and deploying applications (e.g. a condor worker) in a hybrid multi-cloud scenario.
We should evaluate how it compares with Cloud Scheduler.

It looks like the project started in Feb. 2013.

**Comment by mhpx** [comment]
well it would certainly remove having to maintain all the different cloud layers, has a rest style api to abstract all the provisioning. Would probably still need the condor specific aspects of CS

**Comment by rptaylor** [comment]
Some automation and auto-scale features are mentioned; perhaps that could connect to Condor. Aside from that the VMs could just be contextualized to join a standalone Condor system.
http://sixsq.com/products/slipstream-usecases.html#Auto-Scale-and-Mutable-Deployments
"For example, the number of web nodes in a n-tier application can be increased or removed, at the click or a button, a CLI call or a API call. In turn, SlipStream’s automation logic will kick-in to ensure that each layer is being notified, so that for example, the load balancer layer updates its list of web nodes to forward work to, or that the database cluster rebalances itself taking into account new or old nodes.
Following from this mutable feature, monitoring and custom KPI definitions will complete the full auto-scale feature."

**Comment by mhpx** [comment]
> currently working on the ability to support mutable deployments 
Unless their page out of date that feature not quite there yet. Will be interesting to keep an eye on it though.
