### ISSUE TITLE
Simplify onlining/offlining of clouds

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#376]
Over several years of operational experience, there have been various cases of the form:
-a cloud was put offline temporarily but should have been put offline permanently
-a cloud was put offline permanently but should have been put offline temporarily
- a cloud was put offline or offline temporarily and was expected by person A to stay that way for awhile, but person B restarted CS so the cloud status reverted

This can cause operational difficulties when the cloud status changes in an unexpected or undesired way.

One possible improvement would be for cloud_admin to be able to make either permanent or transient changes to cloud status with an additional option.

However, I think it would be much better and more intuitive to completely remove the transient/permanent distinction: 
-the "enabled" property should be removed from cloud_resources.conf (Persistence would be required somewhere else)
-the cloud online/offline status should change if and only if cloud_admin is explicitly invoked, and not on a CS restart.

**Comment by rptaylor** [comment]
This would be a very helpful improvement that would make operations easier.

**Comment by mhpx** [comment]
So, default as off, and track in the normal persistence file for restarts?

**Comment by rptaylor** [comment]
Yeah, "off" seems like the safer default option. cloud_admin would be the one and only way to enable or disable a cloud, and it would always be persistent.
Sound good to everyone?

**Comment by crlb** [comment]
Sounds good. As per Randy's request, I have opened #388 and linked this 
one to it.

On 15-09-01 02:40 PM, rptaylor wrote:
>
> Yeah, "off" seems like the safer default option. cloud_admin would be 
> the one and only way to enable or disable a cloud, and it would always 
> be persistent.
> Sound good to everyone?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hep-gc/cloud-scheduler/issues/376#issuecomment-136869296>.
>

-- 
Colin Leavett-Brown
Physics and Astronomy
University of Victoria
250-472-4085

**Comment by rptaylor** [comment]
Great! Mentioning @ptrlv @richardnixonshead so they'll be aware of the upcoming change.
