### ISSUE TITLE
cloud_admin modification or wrapper to record/log commands with comments.

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloud-scheduler#388]
Command should require a reason/description for the change and maintain a time stamped log of all commands issued as per Ryan T's and Randy's request..

**Comment by rptaylor** [comment]
That's a good idea. We do something like that with our batch worker nodes too. So this information would be logged to a separate file? Like a changelog for tracking incidents?

**Comment by mhpx** [comment]
will use a separate log file, by default going to require all cloud_admin commands to include -C "comment" arg but include option to disable.
