### ISSUE TITLE
Provide default cloud-init user-data (yaml) file(s).

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloud-scheduler#392]
Cloud Scheduler should implement defaults for cloud-init user data files.

A system-wide default cloud-init user data file should be provided in the CS configuration directory; eg. /etc/cloud_scheduler/vm_contextualization.yaml. This file would provide the bare necessities to run batch jobs, ie. the job wrapper script, condor init.d script, required condor configuration parameters, and any commands required to set up the batch environment. This file should also contain the "merge-type" directive so that merging of additional yaml files is enabled by default.

In addition to the system-wide default file, cloud administrators should be able to supply an optional VMAMICONFIG parameter for each cloud definition in the /etc/cloud_scheduler/cloud_resources.conf configuration file, specifying the full path name of additional contextualization files specific to the cloud.

Also, user contextualization files within the user's JDL should still be honoured.

**Comment by rptaylor** [comment]
Sounds good; I would suggest making a subdirectory such as /etc/cloud_scheduler/contextualization for containing the yaml files.

**Comment by mhpx** [comment]
during a pip or setup.py install the template conf files and yaml will go into /usr/local/share/cloudscheduler (default location cs will look if not in conf) if admin needs to change anything they can copy it and set the new location in cloud_scheduler.conf
