### ISSUE TITLE
Remove obsolete classads

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloud-scheduler#393]
When OpenStack VMs are terminated by CS, often the classads for the terminated VMs persist for an extended period; until the Collector cleans them up after some configurable time period (normally 20 to 30 minutes). Thess obsolete classads interfere with the scheduling of jobs on current VMs. CS, which polls the VM classads and tracks VMs, should remove obsolete classads via use of the "condor_advertise" command, thereby improving the scheduling of jobs.

**Comment by mhpx** [comment]
notes: 
general commands: 
condor_advertise INVALIDATE_MASTER_ADS <file> 
condor_advertise INVALIDATE_STARTD_ADS <file>

can use -pool to specify pool other than default local pool
the <file> contains:
MyType="Query"
TargetType="Machine"
Requirements=Name=="<Name value of classad>"  includes the slot1@ part.

can also use -multiple flag and separate entries in the file with a blank line, similar to condor_off will need to do 2 commands, once for master, and once for the startds using -multiple. Will need to create tmp files.

**Comment by mhpx** [comment]
This seems to be working now, will probably adjust the logging some more to be less spammy

**Comment by mhpx** [comment]
May also need to do something to play nice with non CS classads.. but that may not be a priority
