### ISSUE TITLE
Validate yaml user data.

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloud-scheduler#394]
As the user data is read, pass it through a validation filter, something like:

    fd=open(sys.argv[1])
    try:
        yaml.load(fd)
        print 'OK'
    except:
        print 'Error', sys.exc_info()[1]
    fd.close()

If the yaml file fails the test, hold the job and set the reason to "Invalid yaml file", file source, and the sys.exc_info()[1].

**Comment by mhpx** [comment]
will need split up the exception and fetch out e.problem_mark.[name, column, line] to get the filename and position of yaml error

**Comment by mhpx** [comment]
might be causing problems in some of the other yaml file types.
