### ISSUE TITLE
timeout for API calls

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#398]
Currently a Cloud Scheduler thread may hang indefinitely if Openstack does not return a response. We need to have the command time out and fail instead of hanging.

**Comment by mhpx** [comment]
https://github.com/hep-gc/cloud-scheduler/commit/ac70110a9b303c0130771b8e9f28627e27d9c275 
done in dev.
I also edited the pip installed version on condor.heprc with this minor change.

**Comment by mhpx** [comment]
no hangs on belle or condor.heprc since from the looks of it. going to close this issue for now.
