### ISSUE TITLE
Hold job with reason when: VMAMI specifies no image for the selected cloud

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloud-scheduler#401]
eg, cloud "mouse" is selected, but is not mentioned and there is no default in the JDL +VMAMI parameter.

Currently, the job is left idle and CS writes DEBUG log message "None of the resources could boot a vm for job ...'

The job should be held with a reason indicating the problem.

**Comment by mhpx** [comment]
https://github.com/hep-gc/cloud-scheduler/blob/dev/cloud_scheduler#L1137 looks like job will get held if no valid target cloud.
