### ISSUE TITLE
Always shut-down/shut-off prior to instance destroy.

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloud-scheduler#438]
Change the current VM destroy process to the following three step process:

- Shut-down/shut-off
- Wait for shut-down to complete
- Destroy/terminate the VM

Maybe this should be a selectable option per cloud, ie. ShutoffDestroy: True/False

Justification: To provide the opportunity to run (custom) shut-down scripts. These scripts are being used in proto-type benchmarking.

**Comment by mhpx** [comment]
From the dashboard I see Shut Off as an option in the dropdown, but in the python-novaclient api the closest thing to that is stop()

**Comment by mhpx** [comment]
I'm seeing some stuff related to Hard / Soft options, but in the client code I only see that option being available for reboot and not the other operations.

**Comment by mhpx** [comment]
Closing since the need to run custom shutdown script no longer required. 

and it would have been a weird hack to soft reboot then destroy anyways.
