### ISSUE TITLE
Allow default parameters for all CS/JDL paramaters in cloud_scheduler.conf.

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloud-scheduler#439]
Currently identified as missing are: default_VMInjectCA, default_VMKeepAlive, and default_VMUseCloudInit.

**Comment by mhpx** [comment]
A default VMKeepAlive time can be set on a per cloud basis in cloud_resources.conf by adding a time (in minutes) to any cloud entry.

[cloud]
...
keep_alive: 5
...

This was done to give more control over commercial versus 'free' clouds.

**Comment by mhpx** [comment]
UseCloudInit defaults to True and looks like it can be deprecated / removed

**Comment by mhpx** [comment]
default_VMInjectCA already supported.
