### ISSUE TITLE
Missing comma in dependencies for pypi package 1.13

### ISSUE THREAD

**Issue by fderue** [hep-gc/cloud-scheduler#478]
Hi, 
There is a missing comma between keystoneauth1 and python-novaclient 
    install_requires=[
        "boto>=2.38.0",
        "requests>=2.2.0",
        "web.py>=0.3",
        "boto3",
        "botocore",
        "keystoneauth1"
        "python-novaclient>=9.0.0",
        ],

Therefore the pypi pacakge 1.13 can not be installed (I guess it is from the github tag 1.13, since the error is there too but not in the master branch)

**Comment by mhpx** [comment]
thanks for catching that.
a new version has been uploaded to pypi
https://pypi.python.org/pypi/cloud-scheduler/1.13.1
